/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package administrabancos;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *s
 * @author helio
 */
public class JanelaModificao extends javax.swing.JFrame {
    private Conexao conexao;
    private DefaultTableModel model;
    private String insercao = "";
    private String nomesColunas = "";
    
    public JanelaModificao(String title) {
        super(title);
        setSize(300, 200);
        initComponents();
        conexao = Conexao.getInstance();
        atualizarColunas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaInsercao = new javax.swing.JTable();
        jBotaoEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabelaInsercao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabelaInsercao.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabelaInsercaoPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTabelaInsercao);

        jBotaoEnviar.setText("Atualizar");
        jBotaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jBotaoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotaoEnviar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoEnviarActionPerformed
        try {
            getInfoTabela();
            
            System.out.println(insercao);
            
            if(model.getColumnName(0).equalsIgnoreCase("id")){
                System.out.println("Tem id");
                conexao.adicionarItemLista(nomesColunas, insercao, conexao.getTableName(), true);
            } else{
                System.out.println("Não tem id");
                conexao.adicionarItemLista(nomesColunas, insercao, conexao.getTableName(), false);
            }
            insercao = "";
            nomesColunas = "";
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JanelaModificao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JanelaModificao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBotaoEnviarActionPerformed

    private void jTabelaInsercaoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabelaInsercaoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabelaInsercaoPropertyChange
    
    public void atualizarColunas(){
        try {
            String tableName = conexao.getTableName();
            String dbName = conexao.getDbName();
            System.out.println("Nomes: " +tableName + " " + dbName);
            
            conexao.conectarBancoEspecifico(dbName);
            model = conexao.getTableModel(dbName, tableName);
            
            limpaColunasDoModel(model);
            jTabelaInsercao.setModel(model);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(GuiBancos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getInfoTabela(){
        int linha = 0;
        for (int i = 0; i < model.getColumnCount(); i++) {
            nomesColunas += model.getColumnName(i) + " ";
            insercao += (String)model.getValueAt(linha, i) + " ";
        }
        
        System.out.println(insercao);
    }
    
    public void limpaColunasDoModel(DefaultTableModel model){
        model.setNumRows(0);
        int numeroColunas = model.getColumnCount();
        String info = "";
        for(int i = 0; i < numeroColunas-1; i++){
            info += ""+ ",";
        }
        model.addRow(new Object[]{});
        System.out.println(info);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotaoEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaInsercao;
    // End of variables declaration//GEN-END:variables
}
